language: dart
sudo: false
dart:
  - dev
script:
  - pub get --packages-dir
  - pub run dependency_validator --ignore dart_style,coverage
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov