name: json_schema2
version: 2.0.0+4
description: Provide support for validating instances against json schema
homepage: https://github.com/workiva/json_schema

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  collection: ^1.15.0
  logging: ^1.0.2
  meta: ^1.7.0
  path: ^1.8.0
  rest_client: ^2.0.1+3
  uri: ^1.0.0

dev_dependencies:
  test: ^1.17.12
