name: json_schema2
version: 1.0.0+1
description: Provide support for validating instances against json schema
homepage: https://github.com/workiva/json_schema

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ">=0.13.7 <2.0.0"
  collection: ^1.14.13
  logging: ^0.11.4
  meta: ^1.2.4
  path: ^1.7.0
  rest_client: ^1.0.6+1
  uri: ^0.11.3+1

dev_dependencies:
  test: any
  test_coverage: any
