name: 'json_schema2'
version: '2.0.2+15'
description: 'Provide support for validating instances against json schema'
homepage: 'https://github.com/peiffer-innovations/json_schema2'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  args: '^2.3.1'
  collection: '^1.16.0'
  logging: '^1.1.0'
  meta: '^1.7.0'
  path: '^1.8.0'
  rest_client: '^2.2.0'
  uri: '^1.0.0'
  yaon: '^1.0.1+5'

dev_dependencies: 
  test: '^1.21.6'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
