name: json_schema
version: 4.0.3
description: JSON Schema implementation in Dart
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  http: ^0.13.1
  logging: ^1.0.1
  rfc_6901: ^0.1.1
  uri: ^1.0.0

dev_dependencies:
  dependency_validator: ^3.1.2
  path: ^1.8.1
  shelf: ^1.1.1
  shelf_static: ^1.1.0
  test: ^1.16.6
  workiva_analysis_options: ^1.2.2
