name: json_schema
version: 2.2.1
description: Provide support for validating instances against json schema
authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^2.0.0
  collection: ^1.14.6
  logging: ^1.0.0
  path: ^1.3.0
  uri: ">=0.11.1 <0.12.0"
  w_transport:
    git:
      url: git@github.com:Workiva/w_transport.git
      ref: flutter-fix-new

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^2.0.0
  build_web_compilers: ^2.9.0
  build_vm_compilers: ^1.0.4
  dart_dev:
    git:
      url: git@github.com:kyleferguson-wk/dart_dev.git
      ref: master
  dart_style: ^1.3.1
  dependency_validator:
    git:
      url: git@github.com:kyleferguson-wk/dependency_validator.git
      ref: master
  glob: ^2.0.0
  shelf: ^1.0.0
  shelf_static: ^0.2.7
  test: ^1.9.1

dependency_overrides:
  build: ^1.0.0